wandb_version: 1

optimizer:
  desc: null
  value: AdamW
learning_rate:
  desc: null
  value: 0.002
b2:
  desc: null
  value: 0.96
num_epochs:
  desc: null
  value: 1
eval_every_n:
  desc: null
  value: 20
batch_size:
  desc: null
  value: 1
max_steps:
  desc: null
  value: 1000
_wandb:
  desc: null
  value:
    python_version: 3.12.3
    cli_version: 0.17.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1719846790
    t:
      1:
      - 55
      2:
      - 1
      - 2
      - 3
      - 12
      - 41
      - 49
      - 51
      - 55
      - 63
      3:
      - 16
      - 23
      4: 3.12.3
      5: 0.17.1
      8:
      - 5
      13: linux-x86_64
    framework: torch
